version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: build/dev/Dockerfile
    image: marcelogaia/homey:nightly
    ports :
      - "8080:8080"
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo
    # command: cargo run
  production:
    build:
      context: .
      dockerfile: build/prod/Dockerfile
    image: marcelogaia/homey:latest
volumes:
  cargo-cache: