name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: nightly
            if: github.ref == 'refs/heads/main'
            tags: marcelogaia/homey:nightly
          - name: release
            if: startsWith(github.ref, 'refs/tags/')
            tags: marcelogaia/homey:latest

    steps:
      - name: Checkout code
        if: ${{ matrix.if }}
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        if: ${{ matrix.if }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        if: ${{ matrix.if }}
        uses: docker/setup-buildx-action@v3

      - name: Extract tag name
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        if: ${{ matrix.if }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build/prod/Dockerfile
          push: true
          tags: |
            ${{ matrix.tags }}
            ${{ env.tag }}