name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: nightly
            image: marcelogaia/homey
            tag: nightly
          - name: release
            image: marcelogaia/homey
            tag: latest

    steps:
      - name: Checkout code
        if: (matrix.name == 'nightly' && github.ref == 'refs/heads/main') || (matrix.name == 'release' && startsWith(github.ref, 'refs/tags/'))
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        if: (matrix.name == 'nightly' && github.ref == 'refs/heads/main') || (matrix.name == 'release' && startsWith(github.ref, 'refs/tags/'))
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        if: (matrix.name == 'nightly' && github.ref == 'refs/heads/main') || (matrix.name == 'release' && startsWith(github.ref, 'refs/tags/'))
        uses: docker/setup-buildx-action@v3

      - name: Extract tag name
        if: matrix.name == 'release' && startsWith(github.ref, 'refs/tags/')
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set tags
        run: |
          echo "tags=${{ matrix.image }}:${{ matrix.tag }}" >> $GITHUB_ENV
          if [[ "${{ matrix.name }}" == "release" ]]; then
            echo "tags=${{ matrix.image }}:${{ matrix.tag }},${{ matrix.image }}:${{ env.version }}" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        if: (matrix.name == 'nightly' && github.ref == 'refs/heads/main') || (matrix.name == 'release' && startsWith(github.ref, 'refs/tags/'))
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build/prod/Dockerfile
          push: true
          tags: ${{ env.tags }}